"""Initial commit

Revision ID: 13096887c88e
Revises: c05447ee482a
Create Date: 2024-11-08 20:07:56.257877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13096887c88e'
down_revision = 'c05447ee482a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_flow')
    op.drop_table('node_connections')
    op.drop_table('network_topology')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_topology',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('network_topology_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('node_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('node_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='network_topology_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('node_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_node_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('destination_node_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('connection_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('connection_properties', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['destination_node_id'], ['network_topology.id'], name='node_connections_destination_node_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['network_topology.id'], name='node_connections_source_node_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='node_connections_pkey')
    )
    op.create_table('traffic_flow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_node', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('destination_node', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('protocol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('packet_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('latency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('flow_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='traffic_flow_pkey')
    )
    # ### end Alembic commands ###
