"""empty message

Revision ID: 14bc046d7064
Revises: 0de1d1b8325f
Create Date: 2024-10-14 12:57:40.182150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bc046d7064'
down_revision = '0de1d1b8325f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detection', schema=None) as batch_op:
        batch_op.drop_constraint('anomaly_detection_related_flow_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'traffic_flow', ['related_flow'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ids_alerts', schema=None) as batch_op:
        batch_op.drop_constraint('ids_alerts_related_attack_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'traffic_flow', ['related_attack'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ids_alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ids_alerts_related_attack_fkey', 'traffic_flow', ['related_attack'], ['id'])

    with op.batch_alter_table('anomaly_detection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('anomaly_detection_related_flow_fkey', 'traffic_flow', ['related_flow'], ['id'])

    # ### end Alembic commands ###
