"""tester database for integration

Revision ID: 1f1e9006a072
Revises: 35ba4670f477
Create Date: 2024-10-19 16:57:58.759903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1e9006a072'
down_revision = '35ba4670f477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=True),
    sa.Column('destination_node_id', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['destination_node_id'], ['network_topology.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['network_topology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_topology', schema=None) as batch_op:
        batch_op.drop_column('connected_nodes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_topology', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connected_nodes', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.drop_table('node_connections')
    # ### end Alembic commands ###
