"""update againnnnn for sample data

Revision ID: 5227b1270d4f
Revises: 016d4f89b1a3
Create Date: 2024-10-20 15:42:57.137957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5227b1270d4f'
down_revision = '016d4f89b1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_properties', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_connections', schema=None) as batch_op:
        batch_op.drop_column('connection_properties')

    # ### end Alembic commands ###
