"""update for sample data

Revision ID: a67682d6f773
Revises: 1f1e9006a072
Create Date: 2024-10-19 17:11:59.284560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67682d6f773'
down_revision = '1f1e9006a072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packet_inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packet_size', sa.Integer(), nullable=True))
        batch_op.drop_column('payload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packet_inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('packet_size')

    # ### end Alembic commands ###
