"""Initial commit

Revision ID: c05447ee482a
Revises: 
Create Date: 2024-11-03 10:51:02.150269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05447ee482a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_topology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=50), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node', sa.String(length=50), nullable=False),
    sa.Column('destination_node', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('packet_size', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('flow_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=True),
    sa.Column('destination_node_id', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.String(length=20), nullable=True),
    sa.Column('connection_properties', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['destination_node_id'], ['network_topology.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['network_topology.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_connections')
    op.drop_table('traffic_flow')
    op.drop_table('network_topology')
    # ### end Alembic commands ###
