"""update again  for sample data

Revision ID: d620a2f19815
Revises: a67682d6f773
Create Date: 2024-10-19 17:14:07.075545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd620a2f19815'
down_revision = 'a67682d6f773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ids_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_flow', sa.Integer(), nullable=True))
        batch_op.drop_constraint('ids_alerts_related_attack_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'traffic_flow', ['related_flow'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('related_attack')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ids_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_attack', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ids_alerts_related_attack_fkey', 'traffic_flow', ['related_attack'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('related_flow')

    # ### end Alembic commands ###
