"""update againnn for sample data

Revision ID: ea17db54a287
Revises: d620a2f19815
Create Date: 2024-10-19 18:24:44.835901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea17db54a287'
down_revision = 'd620a2f19815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_detection', schema=None) as batch_op:
        batch_op.drop_constraint('anomaly_detection_related_flow_fkey', type_='foreignkey')

    with op.batch_alter_table('ids_alerts', schema=None) as batch_op:
        batch_op.drop_constraint('ids_alerts_related_flow_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ids_alerts', schema=None) as batch_op:
        batch_op.create_foreign_key('ids_alerts_related_flow_fkey', 'traffic_flow', ['related_flow'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('anomaly_detection', schema=None) as batch_op:
        batch_op.create_foreign_key('anomaly_detection_related_flow_fkey', 'traffic_flow', ['related_flow'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
